[package]
name = "bali-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "HTTP serverless API gateway (axum)."

[lib]

[dependencies]
anyhow.workspace = true
axum.workspace = true
bali-core = { path = "../bali-core" }
bali-exec = { path = "../bali-exec" }
base64 = "0.22"
dashmap.workspace = true
hyper.workspace = true
opentelemetry = { workspace = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-opentelemetry = { workspace = true }
uuid.workspace = true

[dev-dependencies]
http-body-util = "0.1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-test.workspace = true
tower = { workspace = true, features = ["util"] }
wat.workspace = true
