[package]
name = "bali-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Wasmtime + Tokio async execution engine for Bali instances."

[lib]

[dependencies]
async-trait.workspace = true
bali-core = { path = "../bali-core" }
bali-jit = { path = "../bali-jit" }
bali-mem = { path = "../bali-mem" }
dashmap.workspace = true
futures.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
wasmparser.workspace = true
wasmtime = { workspace = true, features = ["pooling-allocator", "memory-protection-keys"] }
wasmtime-wasi.workspace = true

[dev-dependencies]
tokio-test.workspace = true
tracing-subscriber.workspace = true
wat.workspace = true

[features]
default = ["async-execution"]
async-execution = []
