global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tensor-wasm-api
    static_configs:
      - targets: ["tensor-wasm-api:8080"]
    metrics_path: /metrics
    honor_labels: true
