// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Craton Software Company

//! Cross-version snapshot compatibility tests.
//!
//! This file is the regression guard behind the v0.5 PATH-TO-V1 exit criterion
//! *"v1.0 will read every snapshot produced by v0.5+"* (see
//! `docs/SNAPSHOT-COMPATIBILITY.md`).
//!
//! The tests load checked-in **golden fixtures** — binary blobs produced by
//! the current writer at a fixed timestamp — and assert that the current
//! `SnapshotReader::restore` accepts them, that the on-wire magic + version
//! bytes match the constants in `writer.rs`, and that flipping the version
//! byte by one is rejected. The fixtures are deliberately checked in as bytes
//! rather than regenerated on every test run: their value is precisely that
//! they encode a *frozen* historical wire format.
//!
//! The bytes are generated by `examples/generate_golden.rs`; see
//! `docs/SNAPSHOT-COMPATIBILITY.md` for the exact `cargo run` invocation.
//! Until they have been generated, every test in this file is `#[ignore]`d
//! so a fresh checkout does not fail; the orchestrator un-ignores them once
//! the fixtures are present.
//!
//! Adding a future v0.2 fixture: copy the bytes produced by the *v0.1.0*
//! generator into `tests/fixtures/golden_v0_1_0_*.snap` and check them in.
//! When v0.2 ships with a format bump, write a *new* generator for that
//! version, drop its output into `tests/fixtures/golden_v0_2_0_*.snap`, and
//! add a v0.2-targeted test below. The v0.1.0 fixtures must continue to
//! load — that is the entire compat promise.

use std::fs;
use std::path::{Path, PathBuf};

use tensor_wasm_core::error::TensorWasmError;
use tensor_wasm_core::types::{InstanceId, TenantId};
use tensor_wasm_snapshot::reader::SnapshotReader;
use tensor_wasm_snapshot::writer::{SNAPSHOT_MAGIC, SNAPSHOT_VERSION};

/// Filename of the minimal golden fixture (empty bodies).
const MINIMAL_FIXTURE: &str = "golden_v0_1_0_minimal.snap";
/// Filename of the slightly richer golden fixture (non-empty wasm/gpu/regs).
const RICH_FIXTURE: &str = "golden_v0_1_0_with_wasm_memory.snap";

/// Tenant ID embedded in the minimal fixture (must match
/// `examples/generate_golden.rs`).
const MINIMAL_TENANT_ID: u64 = 0xA;
/// Instance ID embedded in the minimal fixture.
const MINIMAL_INSTANCE_ID: u128 = 0xB;

/// Tenant ID embedded in the richer fixture.
const RICH_TENANT_ID: u64 = 0xC0FF_EE;
/// Instance ID embedded in the richer fixture.
const RICH_INSTANCE_ID: u128 = 0xDEAD_BEEF_CAFE_F00D;

/// Expected `wasm_memory.len()` for the richer fixture (synth_wasm_memory in
/// the generator).
const RICH_WASM_LEN: usize = 4096;
/// Expected `gpu_memory.len()` for the richer fixture.
const RICH_GPU_LEN: usize = 1024;
/// Expected `registers.len()` for the richer fixture.
const RICH_REGISTERS_LEN: usize = 256;

/// Path to the `tests/fixtures` directory, resolved relative to this crate's
/// `CARGO_MANIFEST_DIR` so the tests can be run from any working directory.
fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

/// Load a golden fixture by filename. Panics with a clear message if the
/// fixture is missing — the surrounding tests are `#[ignore]`d until the
/// orchestrator runs `examples/generate_golden.rs` to produce the bytes.
fn load_fixture(name: &str) -> Vec<u8> {
    let path = fixtures_dir().join(name);
    fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "golden fixture {} missing or unreadable: {e}\n\
             Generate it with:\n  \
             cargo run -p tensor-wasm-snapshot --example generate_golden -- \
             crates/tensor-wasm-snapshot/tests/fixtures",
            path.display(),
        )
    })
}

#[test]
#[ignore = "requires committed golden fixtures; see crates/tensor-wasm-snapshot/tests/fixtures/README.md"]
fn minimal_golden_restores_under_current_reader() {
    let bytes = load_fixture(MINIMAL_FIXTURE);
    let restored = SnapshotReader::new()
        .restore(&bytes)
        .expect("minimal golden fixture must restore");

    assert_eq!(restored.magic, SNAPSHOT_MAGIC);
    assert_eq!(restored.version, SNAPSHOT_VERSION);
    assert_eq!(restored.metadata.tenant_id, TenantId(MINIMAL_TENANT_ID));
    assert_eq!(
        restored.metadata.instance_id,
        InstanceId(MINIMAL_INSTANCE_ID)
    );
    assert!(restored.wasm_memory.is_empty());
    assert!(restored.gpu_memory.is_empty());
    assert!(restored.registers.is_empty());
    assert_eq!(restored.metadata.total_uncompressed_bytes, 0);
}

#[test]
#[ignore = "requires committed golden fixtures; see crates/tensor-wasm-snapshot/tests/fixtures/README.md"]
fn rich_golden_restores_under_current_reader() {
    let bytes = load_fixture(RICH_FIXTURE);
    let restored = SnapshotReader::new()
        .restore(&bytes)
        .expect("rich golden fixture must restore");

    assert_eq!(restored.magic, SNAPSHOT_MAGIC);
    assert_eq!(restored.version, SNAPSHOT_VERSION);
    assert_eq!(restored.metadata.tenant_id, TenantId(RICH_TENANT_ID));
    assert_eq!(restored.metadata.instance_id, InstanceId(RICH_INSTANCE_ID));
    assert_eq!(restored.wasm_memory.len(), RICH_WASM_LEN);
    assert_eq!(restored.gpu_memory.len(), RICH_GPU_LEN);
    assert_eq!(restored.registers.len(), RICH_REGISTERS_LEN);
    assert_eq!(
        restored.metadata.total_uncompressed_bytes,
        (RICH_WASM_LEN + RICH_GPU_LEN + RICH_REGISTERS_LEN) as u64,
    );
}

/// Decompress the golden fixture and walk the raw bincode prefix to confirm
/// the on-wire magic + version fields equal the in-source constants.
///
/// This is the regression guard against a silent format break: if someone
/// changes [`SNAPSHOT_MAGIC`] or [`SNAPSHOT_VERSION`] without bumping the
/// fixture, this assertion fails before the round-trip test even runs.
#[test]
#[ignore = "requires committed golden fixtures; see crates/tensor-wasm-snapshot/tests/fixtures/README.md"]
fn raw_magic_and_version_match_source_constants() {
    let bytes = load_fixture(MINIMAL_FIXTURE);
    let decompressed = zstd::decode_all(bytes.as_slice()).expect("zstd decode golden");

    // bincode 1.x default config: little-endian, fixint. The first two fields
    // of `Snapshot` are `magic: u32` then `version: u32`, so the first eight
    // bytes of the decompressed payload are exactly those two integers in
    // little-endian order.
    assert!(
        decompressed.len() >= 8,
        "decompressed payload too short to contain magic + version (len = {})",
        decompressed.len(),
    );
    let magic = u32::from_le_bytes([
        decompressed[0],
        decompressed[1],
        decompressed[2],
        decompressed[3],
    ]);
    let version = u32::from_le_bytes([
        decompressed[4],
        decompressed[5],
        decompressed[6],
        decompressed[7],
    ]);

    assert_eq!(
        magic, SNAPSHOT_MAGIC,
        "on-wire magic {magic:#X} differs from source constant {SNAPSHOT_MAGIC:#X}",
    );
    assert_eq!(
        version, SNAPSHOT_VERSION,
        "on-wire version {version} differs from source constant {SNAPSHOT_VERSION}",
    );
}

/// Decompress the golden fixture, overwrite the on-wire version byte with a
/// value outside the supported set (V2 / V3), re-compress, and confirm the
/// reader refuses the result with a `Serialization` error whose message
/// mentions `version`.
///
/// This is the regression guard against accidentally weakening the version
/// check (e.g. someone making it a warning instead of an error). If this test
/// fails, the reader has lost its strict-version contract and the compat
/// promise in `docs/SNAPSHOT-COMPATIBILITY.md` is no longer enforceable.
///
/// # Implementation note
///
/// The earlier "bump by +1" approach collided with V3: the V2 fixture's
/// version byte was `0x02`, +1 gave `0x03` which equals
/// [`SNAPSHOT_VERSION_V3`](crate::format::SNAPSHOT_VERSION_V3), and the
/// reader then rejected on the signed-snapshot path ("snapshot is signed
/// (v3) but reader has no HMAC key") rather than the version-dispatch
/// catch-all. We now write `V3 + 1` directly, deterministically landing in
/// the "unknown version" branch regardless of which supported version the
/// fixture was minted against.
#[test]
#[ignore = "requires committed golden fixtures; see crates/tensor-wasm-snapshot/tests/fixtures/README.md"]
fn bumped_version_byte_is_rejected() {
    use tensor_wasm_snapshot::format::SNAPSHOT_VERSION_V3;

    let bytes = load_fixture(MINIMAL_FIXTURE);
    let mut decompressed = zstd::decode_all(bytes.as_slice()).expect("zstd decode golden");

    // Bincode `legacy()` config encodes structs as fixint-LE in declaration
    // order, and the `Snapshot` struct begins with `magic: u32, version:
    // u32`. So bytes 0..4 are the magic and 4..8 are the version field.
    assert!(decompressed.len() >= 8, "payload too short");

    // Overwrite the version with V3 + 1 — definitely outside the supported
    // set {V2, V3} and outside any plausible near-future bump. The catch-
    // all arm in `SnapshotReader::restore` should fire with a "version
    // mismatch" message containing the word "version".
    let unsupported_version: u32 = SNAPSHOT_VERSION_V3 + 1;
    decompressed[4..8].copy_from_slice(&unsupported_version.to_le_bytes());

    let recompressed = zstd::encode_all(decompressed.as_slice(), 3).expect("zstd re-encode");

    let err = SnapshotReader::new()
        .restore(&recompressed)
        .expect_err("bumped version must be rejected");

    match err {
        TensorWasmError::Serialization(msg) => {
            assert!(
                msg.contains("version"),
                "expected version rejection, got: {msg}",
            );
        }
        other => panic!("expected Serialization error, got {other:?}"),
    }
}
