---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensor-wasm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tensor-wasm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (gt (int .Values.service.nodePort) 0) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "tensor-wasm.selectorLabels" . | nindent 4 }}
