// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Craton Software Company

//! `tensor-wasm man` — generate roff(7) man pages for every CLI subcommand.
//!
//! Walks the clap `Command` tree, renders one `.1` page per node via
//! [`clap_mangen::Man`], and writes the resulting groff sources either to a
//! caller-supplied directory or to stdout (root page only). The committed
//! scaffolding under `crates/tensor-wasm-cli/man/` is regenerated by:
//!
//! ```bash
//! tensor-wasm man --out-dir crates/tensor-wasm-cli/man
//! ```
//!
//! See `crates/tensor-wasm-cli/man/README.md` for install paths per OS.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Args, Command, CommandFactory};
use clap_mangen::Man;

use crate::Cli;

/// Arguments to `tensor-wasm man`.
#[derive(Debug, Args)]
pub struct ManArgs {
    /// Output directory. When omitted, only the root `tensor-wasm.1` page is
    /// emitted to stdout. When provided, every subcommand gets its own page
    /// written as `<binary>-<subcommand>.1` (matching the established
    /// convention used by `git-status.1`, `cargo-build.1`, etc.).
    #[arg(long)]
    pub out_dir: Option<PathBuf>,
}

/// Entry point for `tensor-wasm man`.
pub fn run(args: ManArgs) -> Result<()> {
    let cmd = Cli::command();
    match args.out_dir {
        None => {
            // Stdout: emit only the root page. Multi-page emission to stdout
            // would interleave roff sources without a separator and confuse
            // every downstream tool.
            let man = Man::new(cmd);
            man.render(&mut io::stdout())
                .context("rendering tensor-wasm.1 to stdout")?;
        }
        Some(dir) => {
            ensure_dir(&dir)?;
            let pages = render_tree(&cmd, &dir)?;
            for path in &pages {
                println!("wrote {}", path.display());
            }
        }
    }
    Ok(())
}

/// Render the root command and every subcommand into `out_dir`. Returns the
/// list of files written, in deterministic depth-first order so the printed
/// output is stable across runs.
fn render_tree(root: &Command, out_dir: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    let root_name = root.get_name().to_string();

    // Root page.
    let root_path = out_dir.join(format!("{root_name}.1"));
    write_page(root.clone(), &root_path)?;
    out.push(root_path);

    // Subcommands. We only render the first depth so the committed set
    // matches the `tensor-wasm <verb>` surface; `snapshot save` / `snapshot restore`
    // are documented inside `tensor-wasm-snapshot.1` itself rather than as separate
    // pages, which matches the convention used by `git-remote.1`.
    for sub in root.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        let sub_name = sub.get_name();
        // clap_mangen renders headings off the command's display name; force
        // the per-page filename to be `<root>-<sub>.1` so cross-referencing
        // works (see CONVENTIONS in man-pages(7)).
        let path = out_dir.join(format!("{root_name}-{sub_name}.1"));
        // Re-build a Command with a display name that includes the parent
        // segment so SYNOPSIS reads `tensor-wasm run [OPTIONS]` rather than
        // bare `run [OPTIONS]`. `Command::name` takes `impl Into<Str>`, and
        // clap 4.6 only implements `From<&'static str>` for `Str` — not
        // `From<String>` — so we leak a Box<str> per subcommand. Bounded
        // leak: at most ~10 subcommand names × <32 B each per process call.
        let display_name: &'static str =
            Box::leak(format!("{root_name}-{sub_name}").into_boxed_str());
        let composed = sub.clone().name(display_name);
        write_page(composed, &path)?;
        out.push(path);
    }
    Ok(out)
}

/// Render one clap `Command` into a `.1` file via `clap_mangen::Man`.
fn write_page(cmd: Command, path: &Path) -> Result<()> {
    let man = Man::new(cmd);
    let mut buffer: Vec<u8> = Vec::new();
    man.render(&mut buffer)
        .with_context(|| format!("rendering {}", path.display()))?;
    fs::write(path, &buffer).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Create `dir` (and any missing parents) so the first regen on a fresh
/// checkout succeeds.
fn ensure_dir(dir: &Path) -> Result<()> {
    if dir.exists() {
        let meta =
            fs::metadata(dir).with_context(|| format!("stat'ing --out-dir {}", dir.display()))?;
        if !meta.is_dir() {
            anyhow::bail!("--out-dir {} exists but is not a directory", dir.display());
        }
        return Ok(());
    }
    fs::create_dir_all(dir).with_context(|| format!("creating --out-dir {}", dir.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn renders_root_and_subcommand_pages() {
        let tmp = tempdir().unwrap();
        let cmd = Cli::command();
        let pages = render_tree(&cmd, tmp.path()).unwrap();
        // Root page + at least the seven first-depth subcommands declared in
        // `crate::Command`.
        assert!(pages.len() >= 8, "got {} pages", pages.len());
        // Root page exists and is non-empty.
        let root = tmp.path().join("tensor-wasm.1");
        let body = fs::read_to_string(&root).unwrap();
        assert!(body.contains(".TH"), "missing .TH header: {body}");
    }

    #[test]
    fn ensure_dir_rejects_non_directory() {
        let tmp = tempdir().unwrap();
        let file = tmp.path().join("not-a-dir");
        fs::write(&file, b"x").unwrap();
        assert!(ensure_dir(&file).is_err());
    }
}
